apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  labels:
    app: api
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: my-basic-auth
    # adapt to networking.k8s.io/v1
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.gengo.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
